### ISSUE TITLE
error This signal-cli-rest-api version is not capable of sending multiple attachments.

### ISSUE THREAD

**Issue by limitless-code** [bbernhard/signal-cli-rest-api#10]
Error in Home Assistant after upgrading to 0.106.5

```
The 'attachment' option is deprecated, please replace it with 'attachments'. This option will become invalid in version 0.108.
```
changed 'attachment' to 'attachments' and get the following in the home assistant logs:

```
Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 397, in async_trigger
    await self.action_script.async_run(variables, trigger_context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 185, in async_send_message
    await self.hass.async_add_job(partial(self.send_message, message, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 38, in send_message
    raise SignalCliRestApiError("This signal-cli-rest-api version is not capable of sending multiple attachments. Please upgrade your signal-cli-rest-api docker container!")
```
when attempting to trigger an automation the following appears on the signal docker side:

signal-cli-rest-api_1  | [GIN] 2020/03/04 - 19:30:58 | 404 |      21.463µs |   <ip address> | GET      /v1/about

Thanks!

**Comment by bbernhard** [comment]
Hi, 

have you tried pulling the latest docker image from dockerhub? (don't forget to restart your docker container afterwards) This should resolve the issue. Please let me know in case it doesn't work.

**Comment by limitless-code** [comment]
Thanks for responding so quickly!

I assumed that the following 'image: bbernhard/signal-cli-rest-api:latest' in the docker-compose.yml would pull the latest version on 'docker-compose up' which is why I thought I was on the latest.

I ran the following command:

```
docker pull bbernhard/signal-cli-rest-api
```

which pulled the latest version.

I reverted to 'attachments' for the new version of HA instead of 'attachment' and get the following on the signal side which is different to before the latest version was pulled:

```
signal-cli-rest-api_1  | [GIN] 2020/03/04 - 20:19:33 | 200 |     785.725µs |   <ip address> | GET      /v1/about
```

which is good, but nothing else is returned.

Home Assistant shows the following in the logs:

```
Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 56, in send_message
    with open(filename, "rb") as ofile:
IsADirectoryError: [Errno 21] Is a directory: '/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 397, in async_trigger
    await self.action_script.async_run(variables, trigger_context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 185, in async_send_message
    await self.hass.async_add_job(partial(self.send_message, message, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 71, in send_message
    raise SignalCliRestApiError("Couldn't send signal message") from exc
pysignalclirestapi.api.SignalCliRestApiError: Couldn't send signal message
```

**Comment by bbernhard** [comment]
> I assumed that the following 'image: bbernhard/signal-cli-rest-api:latest' in the docker-compose.yml would pull the latest version on 'docker-compose up' which is why I thought I was on the latest.

Yeah, that's a bit misleading with docker. docker-compose doesn't automatically update the docker images when you do a `docker-compose up`. In order to pull the latest image, one has to do do a `docker-compose pull` followed by a `docker-compose restart`.  

This error looks odd: 

```
Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 56, in send_message
    with open(filename, "rb") as ofile:
IsADirectoryError: [Errno 21] Is a directory: '/'
```

Are you sure, that the attachment you are trying to send is actually there? (and it's really a file and not e.g a folder)

Are you trying to send a signal message via HA automation? If so, could you maybe try to send it via the Home Assistant developer tools (just to rule out any side effects from the automation script) and please post the YAML service data you are using here.

**Comment by limitless-code** [comment]
It's back working! 

changed config in HA automation to:

```
attachments: 
          - "/test/image.png"
```
instead of 'attachments: /test/image.png'

Many thanks! @bbernhard . I have found this API extremely useful and fills me with confidence my messages are going via signal (encrypted) instead email!

**Comment by bbernhard** [comment]
> It's back working!
> 
> changed config in HA automation to:
> 
> ```
> attachments: 
>           - "/test/image.png"
> ```
> 
> instead of 'attachments: /test/image.png'
> 
> Many thanks! @bbernhard . I have found this API extremely useful and fills me with confidence my messages are going via signal (encrypted) instead email!

Yeah, unfortunately had to change the API slightly in order to support multiple attachments. I wish I had planned for multiple attachments in the first place, but yeah...:D 

Glad you got it working & thanks for the kind words!

**Comment by limitless-code** [comment]
No worries. I shall put 'docker-compose pull' in my systemd script so it will try to pull the latest version each time the service starts then run 'docker-compose up'....not sure if this is a good idea but will give it a go! Thanks

**Comment by bbernhard** [comment]
> No worries. I shall put 'docker-compose pull' in my systemd script so it will try to pull the latest version each time the service starts then run 'docker-compose up'....not sure if this is a good idea but will give it a go! Thanks

you're welcome. :) (you could also have a look at watchtower: https://github.com/containrrr/watchtower/ which has some nice additional features like notifications.)
