### ISSUE TITLE
Native mode: Field id_ for org.whispersystems.signalservice.internal.push.SignalServiceProtos$GroupContext not found

### ISSUE THREAD

**Issue by greyivy** [bbernhard/signal-cli-rest-api#121]
I get the following error after enabling native mode on a Home Assistant installation. Running version 0.37.2 on amd64.

```Failed to call service notify/signal. Exception in thread "main" java.lang.RuntimeException: Field id_ for org.whispersystems.signalservice.internal.push.SignalServiceProtos$GroupContext not found. Known fields are [] at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:608) at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:502) at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221) at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77) at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71) at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93) at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107) at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170) at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:386) at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:394) at org.whispersystems.signalservice.api.SignalServiceMessageSender.createGroupContent(SignalServiceMessageSender.java:1303) at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMessageContent(SignalServiceMessageSender.java:701) at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:353) at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1288) at org.asamk.signal.manager.Manager.sendGroupMessage(Manager.java:685) at org.asamk.signal.manager.Manager.sendGroupMessage(Manager.java:662) at org.asamk.signal.dbus.DbusSignalImpl.sendGroupMessage(DbusSignalImpl.java:136) at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:105) at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:15) at org.asamk.signal.App.handleLocalCommand(App.java:204) at org.asamk.signal.App.init(App.java:164) at org.asamk.signal.Main.main(Main.java:49) ```

**Comment by bbernhard** [comment]
Sorry for the late reply. _Could_ be related to https://github.com/AsamK/signal-cli/issues/572

**Comment by bbernhard** [comment]
Could you please try it again with the recently released Version 0.38?

**Comment by bbernhard** [comment]
Closing due to inactivity. Please re-open in case the issue still exists.
