### ISSUE TITLE
Scheduler uses hard coded port 8080

### ISSUE THREAD

**Issue by mes85** [bbernhard/signal-cli-rest-api#135]
I installed signal-cli-rest-api recently. I needed to change the port, because 8080 was already used. It worked, but I noticed crashed in the docker logs.

```
time="2021-05-22T08:49:00+02:00" level=error msg="AUTO_RECEIVE_SCHEDULE: Couldn't call receive for number +49XXXX: Get \"http://127.0.0.1:8080/v1/receive/+49XXXX\": dial tcp 127.0.0.1:8080: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5b1ce8]

goroutine 10 [running]:
main.main.func1.1(0x1f00440, 0x31, 0x7d2330, 0x1cfa6c0, 0x0, 0x0, 0xe36d8, 0x1cfa6c0)
        /tmp/signal-cli-rest-api-src/main.go:175 +0x134
path/filepath.walk(0x1f00440, 0x31, 0x7d2330, 0x1cfa6c0, 0x6ed460, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:360 +0x308
path/filepath.walk(0x1c921b0, 0x22, 0x7d2330, 0x1cfa630, 0x6ed460, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x20c
path/filepath.walk(0xbec4ae48, 0x1d, 0x7d2330, 0x1cfa120, 0x6ed460, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x20c
path/filepath.Walk(0xbec4ae48, 0x1d, 0x6ed460, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:406 +0xe8
main.main.func1()
        /tmp/signal-cli-rest-api-src/main.go:167 +0x30
github.com/robfig/cron/v3.FuncJob.Run(0x218c570)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1c
github.com/robfig/cron/v3.(*Cron).startJob.func1(0x1dcc180, 0x7cb188, 0x218c570)
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x58
created by github.com/robfig/cron/v3.(*Cron).startJob
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x58
```

The port is still 8080 in the scheduler call.

This can also be seen in the source:
```
log.Debug("AUTO_RECEIVE_SCHEDULE: Calling receive for number ", filename)
resp, err := http.Get("http://127.0.0.1:8080/v1/receive/"+filename)
```
(https://github.com/bbernhard/signal-cli-rest-api/blob/master/src/main.go#L171)

**Comment by bbernhard** [comment]
Many thanks for the bug report - completely forgot about the port override!

Should be fixed now. I'll push a new image to dockerhub in the next days.

**Comment by bbernhard** [comment]
there's now a new image on dockerhub which contains the fix
