### ISSUE TITLE
use_voice not working

### ISSUE THREAD

**Issue by hakanalpp** [bbernhard/signal-cli-rest-api#197]
### The problem

Hi, I am using the image `bbernhard/signal-cli-rest-api:latest`

I got the .yml file in the readme ([This one](https://github.com/bbernhard/signal-cli-rest-api#example)), and running using `docker-compose up`.

And using the below curl request. When there is no use_voice option or use_voice is set to false, SMS comes successfully. 
But I have a landline number so I must use the use_voice option. When use_voice is true nothing happens (No SMS or call). 

`curl -X POST -H "Content-Type: application/json" -d '{"use_voice": true, "captcha":"my_captcha"}' 'http://127.0.0.1:8080/v1/register/<mynumber>'`

In console output says that

`signal-cli-rest-api_1  | [GIN] 2022/01/11 - 18:09:38 | 201 |  7.026928293s |      172.21.0.1 | POST     "/v1/register/<mynumber>"`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Could be a problem with the Signal Server (I remember that the server had some issues in the past which impacted registration via voice). Can you please try to connect to the running docker container and invoke `signal-cli` directly. That should give you some more details. See [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md)

**Comment by hakanalpp** [comment]
Still not working.

The current image uses the signal-cli v9.2.0. Tried to build your Dockerfile since it seems to build with v10.0.0 but getting the following error

`COPY ext/libraries/libsignal-client/v${LIBSIGNAL_CLIENT_VERSION} /tmp/libsignal-client-libraries`

**Comment by bbernhard** [comment]
> Still not working

do you see any output that indicates what the problem could be?

**Comment by hakanalpp** [comment]
> do you see any output that indicates what the problem could be?

Nothing unusual in the API. 

Since it is also not working in the signal-cli, this should be a signal-CLI v9.2.0 problem. (I also tested it using SMS and it works)

There is also no output in the signal-cli too.

**Comment by hakanalpp** [comment]
Here is the output using --verbose

```
2022-01-11T19:14:39.565Z [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.9.7
2022-01-11T19:14:45.929Z [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
```

**Comment by bbernhard** [comment]
Hmm, ok, that's unfortunately not very much output. 

> The current image uses the signal-cli v9.2.0. Tried to build your Dockerfile since it seems to build with v10.0.0 but getting the following error

I've just kicked off a dev image build. https://github.com/bbernhard/signal-cli-rest-api/actions/runs/1684229035
Once it is finished, there should be a new image on dockerhub with the tag `bbernhard/signal-cli-rest-api:0.88-dev`. This one should contain signal-cli v0.10.0

**Comment by bbernhard** [comment]
btw: `signal-cli` stores the it's config on the filesystem. So if you already tried to register/registered a number with SMS verification, it's a good idea to completely remove the signal-cli config directory and start from scratch.

**Comment by hakanalpp** [comment]
> btw: signal-cli stores the it's config on the filesystem. So if you already tried to register/registered a number with SMS verification, it's a good idea to completely remove the signal-cli config directory and start from scratch.

Already tried. Waiting for the new v10.0.0 image. Will test and get back to you

**Comment by hakanalpp** [comment]
Sadly it is still not working, but at least we have a better output this time.

```
2022-01-11T20:04:02.725Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2022-01-11T20:04:02.734Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2022-01-11T20:04:02.867Z [main] INFO LibSignal - [libsignal-client]: rust/bridge/jni/src/logging.rs:161: Initializing libsignal-client version:0.11.0
2022-01-11T20:04:07.122Z [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Creating new recipient store.
2022-01-11T20:04:07.129Z [main] DEBUG org.asamk.signal.manager.storage.senderKeys.SenderKeySharedStore - Creating new shared sender key store.
2022-01-11T20:04:07.154Z [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2022-01-11T20:04:07.178Z [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Adding new recipient RecipientId[id=1] with address RecipientAddress[uuid=Optional.empty, number=Optional[<PHONE NUMBER>]]
Request verify error: [413] Rate limit exceeded: 413
org.whispersystems.signalservice.api.push.exceptions.RateLimitException: [413] Rate limit exceeded: 413
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1709)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1693)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1675)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1664)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1600)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1588)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestVoiceVerificationCode(PushServiceSocket.java:330)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestVoiceVerificationCode(SignalServiceAccountManager.java:272)
        at org.asamk.signal.manager.RegistrationManager.register(RegistrationManager.java:175)
        at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:66)
        at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:42)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:237)
        at org.asamk.signal.App.init(App.java:194)
        at org.asamk.signal.Main.main(Main.java:53)
```

**Comment by bbernhard** [comment]
Looks like it might be this issue here: https://github.com/AsamK/signal-cli/issues/161

> There is an HTTP 413 code returned from signal-server when you are trying to register / re-register too many times in a day.

**Comment by hakanalpp** [comment]
I will try tomorrow and let you know

**Comment by bbernhard** [comment]
> Maybe I should create a ticket in signal-cli, it can be related to the Turkish number too.

Yeah, I am afraid I can't help you much here. I think the best would be to open a signal-cli ticket with the output you got and the signal-cli command you executed.
