### ISSUE TITLE
Temporary File Space Issues

### ISSUE THREAD

**Issue by WeldFire** [bbernhard/signal-cli-rest-api#262]
### The problem

Hello All,

I have encountered an error that will prohibit the sending of messages.

Error Log
```
{"error":"java.lang.ExceptionInInitializerError
	at org.asamk.signal.manager.config.ServiceConfig.isSignalClientAvailable(ServiceConfig.java:52)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:58)
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: /tmp/resource3977535907066255691.so: No space left on device
	at org.signal.libsignal.internal.Native.loadLibrary(Native.java:62)
	at org.signal.libsignal.internal.Native.\u003cclinit\u003e(Native.java:67)
	... 3 more
Caused by: java.nio.file.FileSystemException: /tmp/resource3977535907066255691.so: No space left on device
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.nio.file.Files.newByteChannel(Files.java:380)
	at java.nio.file.Files.createFile(Files.java:658)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
	at java.nio.file.Files.createTempFile(Files.java:923)
	at org.signal.libsignal.internal.Native.copyToTempFileAndLoad(Native.java:29)
	at org.signal.libsignal.internal.Native.loadLibrary(Native.java:56)
	... 4 more
"}
```

Docker Config
```YAML
signal-cli-rest-api:
    container_name: signal-cli
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - TZ=America/Chicago
      - MODE=native #supported modes: json-rpc, native, normal
    ports:
      - 8081:8080
    volumes:
      - /mnt/shared/signal-cli/:/home/.local/share/signal-cli
    restart: always
```

Without looking into the code yet; It appears to me that there might be an issue with the receive functionality. 
Making subsequent requests to receive will continually add temporary files if they aren't cleared before the next call is made.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
That's odd - haven't seen this issue before. Could you please try the newest version (which I haved released a few moments ago). Does it work? Do you only get the error in `native` mode?

**Comment by WeldFire** [comment]
Hi @bbernhard sorry for the delayed reply, it appears to still happen in `normal` mode as well.

It is fairly easy to reproduce by hitting the receive endpoint a few times:
![image](https://user-images.githubusercontent.com/293969/185766378-5037e2a5-5598-49ea-8d9a-9987788f2084.png)

It appears that signal-cli fails to clear `resource00000000000000000000.so` in my tests
![image](https://user-images.githubusercontent.com/293969/185766459-0239b3d0-b8bd-442e-986b-6ad6a4b7ec07.png)
These eventually do get cleared somewhat, but they don't clear all the way
![image](https://user-images.githubusercontent.com/293969/185766684-a645b895-cdbc-400f-817f-a04195a22bc0.png)

I haven't been able to reproduce this manually in either mode, but I do also usually see a build up of temporary database locks when running for a prolonged period of time in `native` mode.

**Comment by bbernhard** [comment]
There were some big refactorings in the past months. If you still experience any issues, please create a new issue.
