### ISSUE TITLE
Certificate trust issue

### ISSUE THREAD

**Issue by GSStahl** [bbernhard/signal-cli-rest-api#299]
### The problem

Hi! I have been using this docker image for over a year without any issues, and it has been great.

But approximately 12 hours ago I started getting a problem with an SSL Handshake. Whenever I use a method that tries to talk to the actual signal server (e.g. /v1/receive/<number> or /v1/register/) I get the following response:
{"error":"Request verify error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n"}

Local api-methods such as /v1/configuration works without issue. I tried doing a complete reset by deleting the cloned folder and cloning it again to get the most recent version, but the issue remains. 

I'm assuming that the issue is with the trust store in the docker-image. (The trust store of my ubuntu server host shouldn't matter, right?)

Has anyone else noticed a similar issue or is this an issue only with my application? Does anyone know a fix?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by Cempakers87** [comment]
I have same error as well especially when getting groups and send message to personal.

@GSStahl what version did you use anyway?

**Comment by GSStahl** [comment]
@Cempakers87 I'm not at the server at the moment so I can't check the version number, but I pulled the latest source this morning with: git clone https://github.com/bbernhard/signal-cli-rest-api.git

So I'm assuming the latest release.

**Comment by alessios** [comment]
I have the very same issue with an old (0.41) version since this morning

**Comment by spadaal** [comment]
Updating to the latest (0.64) version solved the issue.

**Comment by Cempakers87** [comment]
@spadaal after I've updated to the latest version, auto receive schedule not working. what shoud I do now? please refer to the following message:
`java.lang.AssertionError: Must have either a ServiceId or E164 number!
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:28)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:33)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:49)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientLocked(RecipientStore.java:743)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:177)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:47)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:264)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:235)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:132)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:109)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:957)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:940)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:71)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)`
