### ISSUE TITLE
Must have either a ServiceId or E164 number

### ISSUE THREAD

**Issue by Cempakers87** [bbernhard/signal-cli-rest-api#301]
### The problem

Hello, please help what should I do if facing issue like the following?
I've just updated to latest version from old version. 

`java.lang.AssertionError: Must have either a ServiceId or E164 number!
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:28)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:33)
        at org.asamk.signal.manager.storage.recipients.RecipientAddress.<init>(RecipientAddress.java:49)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientLocked(RecipientStore.java:743)
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:177)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:47)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:264)
        at org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:235)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:132)
        at org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:109)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:957)
        at org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:940)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:71)
        at org.asamk.signal.App.handleLocalCommand(App.java:282)
        at org.asamk.signal.App.init(App.java:222)
        at org.asamk.signal.Main.main(Main.java:60)`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

other

**Comment by Cempakers87** [comment]
Ah, apologize not giving more information. I facing the issue when execute `receive` command.

**Comment by bbernhard** [comment]
How old was the version you were updating from? What's the architecture of your host system?

**Comment by spadaal** [comment]
Hi, we are facing the same issue after updating from 0.41 to latest (on linux debian stable amd64)

**Comment by spadaal** [comment]
I confirm that cleaning the signal-cli-data dir and re-registering the device solved the issue: thank you for pointing it out and for this brilliant software.

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
