### ISSUE TITLE
signal-cli-native is not supported on arm64 system

### ISSUE THREAD

**Issue by brozikcz** [bbernhard/signal-cli-rest-api#336]
### The problem

Hi guys,

I want to run docker version of signal-cli-rest-api in `native` mode but the system still fallbacks into `normal` mode.

If I checked the path of the native lib in the docker image:

```
ls: cannot access '/usr/bin/signal-cli-native': No such file or directory
```

logs from docker:
```
docker logs -f signal-api
+ set -e
+ [ -z /home/.local/share/signal-cli ]
+ usermod -u 1000 signal-api
usermod: no changes
+ groupmod -g 1000 signal-api
+ chown 1000:1000 -R /home/.local/share/signal-cli
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ native = json-rpc ]
+ hostname -I
+ awk {print $1}
+ export HOST_IP=172.17.0.3
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
time="2023-02-03T06:43:55Z" level=info msg="Started Signal Messenger REST API"
time="2023-02-03T06:43:55Z" level=error msg="signal-cli-native is not support on this system...falling back to signal-cli"
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

**Comment by brozikcz** [comment]
I builded docker image locally but I got:

```
signal-api@29b494e3e6a2:/$ signal-cli-native --verbose --config /home/.local/share/signal-cli/ link -n signal-api
2023-02-08T09:57:53.016Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-02-08T09:57:53.251Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.17.0
2023-02-08T09:57:53.465Z [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:27122409] connect()
2023-02-08T09:57:54.255Z [OkHttp https://chat.signal.org/...] WARN  LibSignal - [WebSocketConnection]: [provisioning:27122409] onFailure()
java.net.ProtocolException: Expected HTTP 101 response but was '499 499'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

2023-02-08T09:57:54.256Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:27122409] Client not null when closed
Link request error: Connection closed!
java.io.IOException: Connection closed!
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.readRequest(WebSocketConnection.java:199)
	at org.whispersystems.signalservice.internal.push.ProvisioningSocket.readRequest(ProvisioningSocket.java:70)
	at org.whispersystems.signalservice.internal.push.ProvisioningSocket.getProvisioningUuid(ProvisioningSocket.java:48)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceUuid(SignalServiceAccountManager.java:526)
	at org.asamk.signal.manager.ProvisioningManagerImpl.getDeviceLinkUri(ProvisioningManagerImpl.java:91)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:45)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:228)
	at org.asamk.signal.App.init(App.java:182)
	at org.asamk.signal.Main.main(Main.java:58)
```
