### ISSUE TITLE
Problem with sending messages

### ISSUE THREAD

**Issue by promokodio** [bbernhard/signal-cli-rest-api#391]
### The problem

Hi!
I have an issue with sending messages to phone numbers:

INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
WARN  RecipientHelper - CDSI request failed, trying fallback to CDS
java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:579)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:164)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:113)
	at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUser(RecipientHelper.java:129)
	at org.asamk.signal.manager.helper.RecipientHelper.lambda$resolveRecipient$0(RecipientHelper.java:91)
	at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:206)
	at org.asamk.signal.manager.helper.RecipientHelper.resolveRecipient(RecipientHelper.java:89)
	at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:456)
	at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:561)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:200)
	at org.asamk.signal.App.handleLocalCommand(App.java:289)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Failed to send (some) messages:
+XXXXXXXXXXXX: Unregistered user "+XXXXXXXXXXXX"
1691445763482
Failed to send message

Tell me please how i can solve it?
Thank you!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
From the error message it looks like, that you haven't registered the number yet?!

**Comment by mrfenyx** [comment]
I have a similar issue where this stopped working all of a sudden. I will try to re-register my number and see if it stays working afterwards.

**Comment by beimoe** [comment]
same on my side

**Comment by mrfenyx** [comment]
Re-registering made everything work again

**Comment by bbernhard** [comment]
please try with the latest version and create another issue in case the problem still exists

**Comment by Emerson-Lazellari** [comment]
Im having this issue as well. I can send individual messages to phone numbers, but when entering the group ID I get this error.
