### ISSUE TITLE
Timeout reached

### ISSUE THREAD

**Issue by romain563** [bbernhard/signal-cli-rest-api#422]
### The problem

Since the last update, Signal addons didn't work anymore.

I've got this errors in this HASS log : 

Logger: homeassistant.components.signal_messenger.notify
Source: components/signal_messenger/notify.py:108
Integration: signal_messenger ([documentation](https://www.home-assistant.io/integrations/signal_messenger), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+signal_messenger%22))
First occurred: 07:28:07 (2 occurrences)
Last logged: 07:43:26
process killed as timeout reached

also : 
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 07:28:07 (2 occurrences)
Last logged: 07:43:26

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: process killed as timeout reached
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 264, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 240, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

-----

Logger: homeassistant.components.websocket_api.http.connection
Source: components/signal_messenger/notify.py:104
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:28:08 (2 occurrences)
Last logged: 07:43:26

[140110941607488] Error handling message: Unknown error (unknown_error) Romain from 86.211.82.210 (Mozilla/5.0 (Linux; Android 13; CPH2447 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; CPH2447))
[140111019791168] Error handling message: Unknown error (unknown_error) Romain from 86.211.82.210 (Mozilla/5.0 (Linux; Android 13; CPH2447 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; CPH2447))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 727, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 264, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 240, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

---

Logger: homeassistant.components.shell_command
Source: components/shell_command/__init__.py:94
Integration: Shell Command (documentation, issues)
First occurred: 02:01:00 (3 occurrences)
Last logged: 07:49:02

Timed out running command: `curl -X GET -H 'Content-Type: application/json' 'http://127.0.0.1:8080/v1/receive/+337513xxxx0'`, after: 60s

Could you help for understanding this problem?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried switching to the `native` mode? That one should be much faster.

**Comment by romain563** [comment]
Thank you for your help.

I've got also an issue with the native mode.

When i try to receive, curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/receive/+337*****90'

i've that problem:
the current machine does not support all the cpu features thtat are required by the image [cx8, cmov, fxsr.......]
Please rebulid the executable with an appropriate setting of the -mach option

**Comment by bbernhard** [comment]
I don't know if graalvm supports that, but I am happy to accept pull requests in that regard.

If you have to use the normal mode, you can also increase the receive timeout (e.g `?timeout=100`)

**Comment by romain563** [comment]
Thank you for your answer but it didn't work...


Logger: homeassistant.components.websocket_api.http.connection
Source: components/signal_messenger/notify.py:104
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:28:08 (4 occurrences)
Last logged: 16:26:16

[140110941607488] Error handling message: Unknown error (unknown_error) Romain from 86.211.82.210 (Mozilla/5.0 (Linux; Android 13; CPH2447 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; CPH2447))
[140111019791168] Error handling message: Unknown error (unknown_error) Romain from 86.211.82.210 (Mozilla/5.0 (Linux; Android 13; CPH2447 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; CPH2447))
[140111338677568] Error handling message: Unknown error (unknown_error) Romain from 78.242.62.241 (Mozilla/5.0 (Linux; Android 13; CPH2447 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; CPH2447))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 727, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 264, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 240, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

And

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 07:28:07 (4 occurrences)
Last logged: 16:26:16

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: process killed as timeout reached
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA]. Please rebuild the executable with an appropriate setting of the -march option.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 264, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 240, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached


[GIN] 2023/10/06 - 16:26:16 | 200 |     100.436µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2023/10/06 - 16:26:16 | 400 |   20.954964ms |     172.30.32.1 | POST     "/v2/send

I' think there is a problem for receiving and now I'm blocked by signal for sending.

The messages have not changed

Le 6 octobre 2023 15:38:05 GMT+02:00, "Bernhard B." ***@***.***> a écrit :

**Comment by Cempakers87** [comment]
I have the same problem 'process killed as timeout reached'. After that, I can't even get groups info.

**Comment by bbernhard** [comment]
Is anyone who has the problem using the `signal-cli-rest-api` docker image, or are you all using the Home Assistant Signal Addon? If anyone is using the docker image, could you maybe give `bbernhard/signal-cli-rest-api:0.128-dev` a try?

**Comment by romain563** [comment]
I'm using the homeassistant add-on.


Le 12 octobre 2023 22:10:09 GMT+02:00, "Bernhard B." ***@***.***> a écrit :

**Comment by bbernhard** [comment]
should be fixed with the latest release.
