### ISSUE TITLE
Native mode - arch issue

### ISSUE THREAD

**Issue by rglss** [bbernhard/signal-cli-rest-api#425]
### The problem

When using signal-cli-rest-api (via Home Assistant add-on) v0.69.0, messages can't be sent or received. Any API called result in a 400 error and the following message:

```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA]. Please rebuild the executable with an appropriate setting of the -march option.
```

Appears to be related to the updated native build in the 0.69.0 release. Switching to 'normal' resolves this issue. 

Issue orignally opened here: https://github.com/haberda/hassio_addons/issues/79

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
I've reverted graalvm back to the version that was used before. You are using the Signal Addon, right? I would really appreciate some alpha testing of the docker image `bbernhard/signal-cli-rest-api:0.128-dev` before I create a new release. @haberda Do you maybe have the possibility to create some sort of "beta release" which is based on `bbernhard/signal-cli-rest-api:0.128-dev`?

**Comment by haberda** [comment]
Yes I can. I should have time tomorrow. I have an "edge" repo where untested builds go.

**Comment by ericvitale** [comment]
I'm having the same issue. I can help you test out that image. I can get it running later today.

**Comment by ericvitale** [comment]
Using 'bbernhard/signal-cli-rest-api:0.128-dev' works for me. I am able to now use the api from the command line and from home assistant. I'm not running the signal-api add-on, just having a notify service connect to my running container. 

```
name: signal_notify_eric
platform: signal_messenger
url: "http://10.60.1.90:11380"
number: "+1nnnxxxnnnn"
recipients:
  - "+1nnnyyynnnn"
``` 

That said, I do still get this error in my log, but the messages are being delivered, quickly.

``` 
2023-10-16 10:59:07.127 ERROR (SyncWorker_6) [homeassistant.components.signal_messenger.notify] 1697468346843INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-10-16 10:59:07.128 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 1697468346843INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 264, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 240, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.11/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
```

**Comment by bbernhard** [comment]
@ericvitale 

Thanks for testing!

Regarding your issue: You need to call the `receive` endpoint periodically. If you don't want to do that, you can also use the [Auto Recceive Schedule](https://github.com/bbernhard/signal-cli-rest-api#auto-receive-schedule), which periodically calls the `receive` endpoint for you.

**Comment by RaceAap** [comment]
Ran into this issue today, when changing to native mode.
Now running on bbernhard/signal-cli-rest-api:0.128-dev and that works great.

@bbernhard Do you have any requests for testing this version?

**Comment by bbernhard** [comment]
Should be fixed with the latest official release (version 0.70).

**Comment by ericvitale** [comment]
Thank you.

**Comment by DeltaTangoLima** [comment]
Can confirm v0.7.0 has fixed this problem for me - thanks!
