### ISSUE TITLE
CAPTCHA proof required for sending

### ISSUE THREAD

**Issue by Drengel1990** [bbernhard/signal-cli-rest-api#437]
### The problem

Send message error every time

{"error":"Failed to send (some) messages:\n+********: CAPTCHA proof required for sending to \"+*********\", available options \"PUSH_CHALLENGE, RECAPTCHA\" with challenge token \"5b1a83a9-76cd-4a2d-87af-9bc42438474e\", or wait \"86400\" seconds.\nTo get the captcha token, go to https://signalcaptchas.org/challenge/generate.html\nAfter solving the captcha, right-click on the \"Open Signal\" link and copy the link.\nUse the following command to submit the captcha token:\nsignal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN\n1698908110944\nINFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.\nFailed to send message due to rate limiting\n"}

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

This problem after update to latest

**Comment by joopdo** [comment]
Did you put in the captcha information?



    Register a number (with captcha)

    When you try to register a number, if you receive a response like {"error":"Captcha required for verification (null)\n"} then Signal is requiring a captcha. To register the number you must do the following:
        Go to https://signalcaptchas.org/registration/generate.html
        Open the developer console
        Find the line that looks like this: Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol. Copy the captcha value
        Use it to make the registration call like this:

    curl -X POST -H "Content-Type: application/json" -d '{"captcha":"captcha value"}' 'http://127.0.0.1:8080/v1/register/<number>' or via voice
    curl -X POST -H "Content-Type: application/json" -d '{"captcha":"captcha value","use_voice": true}' 'http://127.0.0.1:8080/v1/register/<number>

**Comment by anotherbridge** [comment]
@joopdo This still appears after successfull verification, due to the rate limiting. I am facing the same issue and when trying to submit the rate limit challenge I will always get an error from the CLI that I performed an "invalid captcha action". Here is what I tried from within the container:

```
signal-cli --config /home/.local/share/signal-cli -v submitRateLimitChallenge --challenge "<token>" --captcha "<captcha>"
```

```
2023-11-02T11:08:00.040Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
2023-11-02T11:08:00.075Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.4
2023-11-02T11:08:00.440Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-02T11:08:01.091Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-02T11:08:01.347Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@4c2cc639
2023-11-02T11:08:01.353Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-02T11:08:10.513Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-02T11:08:10.523Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Submit challenge error: [400] Bad response: 400 : {"code":400,"message":"invalid captcha action"}
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [400] Bad response: 400 : {"code":400,"message":"invalid captcha action"}
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2049)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1993)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1932)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1926)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.submitRateLimitRecaptchaChallenge(PushServiceSocket.java:1148)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.submitRateLimitRecaptchaChallenge(SignalServiceAccountManager.java:914)
	at org.asamk.signal.manager.internal.ManagerImpl.submitRateLimitRecaptchaChallenge(ManagerImpl.java:381)
	at org.asamk.signal.commands.SubmitRateLimitChallengeCommand.handleCommand(SubmitRateLimitChallengeCommand.java:38)
	at org.asamk.signal.commands.CommandHandler.handleLocalCommand(CommandHandler.java:35)
	at org.asamk.signal.App.handleLocalCommand(App.java:278)
	at org.asamk.signal.App.handleCommand(App.java:179)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:61)
```

**Comment by anotherbridge** [comment]
@Drengel1990 Did you interact with the number that is registered to your Signal-API before? On my end I figured out that when I first write a personal message to that number, then call the receive endpoint and try again sending a message the verification disappears and everything works fine. Yet when interacting with a new number I would have to play the same game to being able to send messages...

**Comment by DANgerous25** [comment]
I got around this problem like this:
1. unregister your number (same command as you used to register without captcha, but s/register/unregister)

`curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://<host>:<port>/v1/unregister/<yournumber>'`

3. type a message in your signal app to your signal-cli number (assuming separate number)

5. Run the receive command

`curl -X GET -H "Content-Type: application/json" 'http://<host>:<port>/v1/receive/<yournumber>'`

7. Now retry the send command

`curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "<yournumber>", "recipients": ["<recipientnumber>"]}' 'http://<host>:<port>/v2/send'`

Hope this helps!

**Comment by bbernhard** [comment]
There is now a dedicated endpoint for that: https://bbernhard.github.io/signal-cli-rest-api/#/Accounts/post_v1_accounts__number__rate_limit_challenge

If you get `CAPTCHA proof required for sending to +xxx` message, then use the above REST API command to lift the rate limit restrictions.
