### ISSUE TITLE
dev131: Error linking device: (MissingCapabilitiesException)

### ISSUE THREAD

**Issue by Kuhkaefer** [bbernhard/signal-cli-rest-api#455]
### The problem

Hey :)

When trying to link a device in json-rpc mode using your dev-131, I get an error: 
`"Error linking device: Link request error: StatusCode: 409 (MissingCapabilitiesException)"`

**What I did:**
- start docker in json-rpc mode
`docker run -p 8080:8080 --name signal-api-json-v0.131-dev -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=json-rpc' bbernhard/signal-cli-rest-api:0.131-dev`
- register number using
http://localhost:8080/v1/qrcodelink?device_name=signal-api-dev

**What happened**
- the signal app did not complain, but also did not show the linked device
- the docker logs show `"Error linking device: Link request error: StatusCode: 409 (MissingCapabilitiesException)"` in the debug mode
- I saw at the beginning of the docker logs:
`+ service supervisor start
Starting supervisor:  ERROR.
+ supervisorctl start all`

In v0.69, the errors wouldn't show (normal mode), but the device doesn't link either...
EDIT: same for normal mode in dev-131

Happy to help with more tests, if that helps :)

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Thanks for testing!

That sounds like an issue with signal-cli. I'll update signal-cli to the latest version (which was released two days ago) and then release a new version for testing. Maybe that fixes the issue :)

**Comment by bbernhard** [comment]
Please give this one a try: `bbernhard/signal-cli-rest-api:0.132-dev`

**Comment by Kuhkaefer** [comment]
Thanks!

Unfortunately, the same error occurs with 0.132...

**Comment by bbernhard** [comment]
Could be an upstream issue (see https://github.com/AsamK/signal-cli/issues/1386)


Could you please do what is described [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and post the output here. Please also add the `-v` flag to the signal-cli command in order to get verbose output. Before posting the output here, please make sure to obfuscate any private information (like your number)

**Comment by Kuhkaefer** [comment]
Okay, you were right, it is a signal-cli-issue:

```
2023-11-25T10:51:37.073Z [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:743648472] disconnect()
2023-11-25T10:51:37.091Z [main] INFO  o.a.s.m.i.ProvisioningManagerImpl - Received link information from MY_NUMBER, linking in progress ...
2023-11-25T10:51:37.167Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:743648472] onClosing()
2023-11-25T10:51:37.168Z [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:743648472] onClose()
2023-11-25T10:51:37.282Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-25T10:51:37.459Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@41c07648
2023-11-25T10:51:37.461Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-25T10:51:37.527Z [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-11-25T10:51:38.634Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-25T10:51:38.638Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-11-25T10:51:38.703Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
2023-11-25T10:51:38.705Z [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Added connection org.sqlite.jdbc4.JDBC4Connection@2dc3271b
2023-11-25T10:51:38.705Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
2023-11-25T10:51:39.146Z [main] DEBUG o.a.s.m.i.ProvisioningManagerImpl - Finishing new device registration
2023-11-25T10:51:39.570Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown initiated...
2023-11-25T10:51:39.572Z [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown completed.
Link request error: StatusCode: 409
org.whispersystems.signalservice.internal.push.exceptions.MissingCapabilitiesException: StatusCode: 409
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$0(PushServiceSocket.java:509)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2011)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1949)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:503)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:743)
        at org.asamk.signal.manager.internal.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:148)
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
        at org.asamk.signal.commands.CommandHandler.handleProvisioningCommand(CommandHandler.java:25)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:255)
        at org.asamk.signal.App.handleCommand(App.java:158)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:61)
```
I will create an issue on signal-cli for that

**Comment by EatCroissant** [comment]
Using iphone for link accounts? Try any android phone.

**Comment by BouncySteak** [comment]
Android Version: 13
Signal Version: 6.41.2

Same issue

**Comment by dave7280** [comment]
Same issue here. It is not possible to link device.

**Comment by bbernhard** [comment]
please give the docker image `bbernhard/signal-cli-rest-api:0.133-dev` a try

**Comment by Kuhkaefer** [comment]
works! <3 thank you, that's amazing!

**Comment by bbernhard** [comment]
Glad that it is working! If there are no objections from anybody, I am planning to create a proper release in the next days.

**Comment by BouncySteak** [comment]
Still having issues here with version 0.133-dev
```
signal-api@e764f3a0cb00:/$ signal-cli --config /home/.local/share/signal-cli/  link
sgnl://linkdevice?uuid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO  ProvisioningManagerImpl - Received link information from +17783020099, linking in progress ...
Link request error: [405] Bad response: 405 : {"code":405,"message":"HTTP 405 Method Not Allowed"}
signal-api@e764f3a0cb00:/$
```

**Comment by BouncySteak** [comment]
Still having issues with version 0.133-dev
```
signal-api@e764f3a0cb00:/$ signal-cli --config /home/.local/share/signal-cli/  link
sgnl://linkdevice?uuid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO  ProvisioningManagerImpl - Received link information from +xxxxxxxxxxxxxxxxx, linking in progress ...
Link request error: [405] Bad response: 405 : {"code":405,"message":"HTTP 405 Method Not Allowed"}
signal-api@e764f3a0cb00:/$
```

**Comment by bbernhard** [comment]
Please try to remove the whole signal-cli config folder and zry starting from scratch

**Comment by BouncySteak** [comment]
Deleted docker volumes and created new docker container without local volume
```
version: "3"
services:
  signal-api2:
    image: bbernhard/signal-cli-rest-api:0.133-dev
    environment:
      - MODE=native
    ports:
      - "8081:8080"
#    volumes:
#      - signal-cli-config:/home/.local/share/signal-cli
#volumes:
#  signal-cli-config:
```

Still same outcome. Is there other logs I can post here?
```
signal-api@8c9e67ad847a:/$ signal-cli --config /home/.local/share/signal-cli/ link
sgnl://linkdevice?uuid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO  ProvisioningManagerImpl - Received link information from +xxxxxxxxxx, linking in progress ...
Link request error: [405] Bad response: 405 : {"code":405,"message":"HTTP 405 Method Not Allowed"}
```

**Comment by bbernhard** [comment]
looks like this is already tracked, see https://github.com/AsamK/signal-cli/issues/1399

**Comment by Midas1989** [comment]
> looks like this is already tracked, see [AsamK/signal-cli#1399](https://github.com/AsamK/signal-cli/issues/1399)

Is fixed

**Comment by bbernhard** [comment]
should be fixed with the latest version
