### ISSUE TITLE
Fatal error: concurrent map writes

### ISSUE THREAD

**Issue by KyryloKrasiuk** [bbernhard/signal-cli-rest-api#493]
### The problem

In json-rpc mode, when several clients are connected to `/v1/receive/+000000000000`, the container crashes with an error:

```
fatal error: concurrent map writes

goroutine 58 [running]:

github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000502ea0, {0xcfdba0?, 0xc000db01c0}, 0xc000da8300)

/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd

net/http.serverHandler.ServeHTTP({0xc0004d0c90?}, {0xcfdba0?, 0xc000db01c0?}, 0x6?)

/usr/local/go/src/net/http/server.go:2938 +0x8e

net/http.(*conn).serve(0xc0004cfd40, {0xcff6c0, 0xc0004581e0})

/usr/local/go/src/net/http/server.go:2009 +0x5f4

created by net/http.(*Server).Serve in goroutine 1

/usr/local/go/src/net/http/server.go:3086 +0x5cb

goroutine 107 [runnable]:

internal/syscall/unix.GetRandom({0xc0002d64d0?, 0x10?, 0x10?}, 0x0?)

/usr/local/go/src/internal/syscall/unix/getrandom.go:21 +0xbe

crypto/rand.getRandom({0xc0002d64d0?, 0x10, 0x0?})

/usr/local/go/src/crypto/rand/rand_getrandom.go:40 +0x1f

crypto/rand.init.0.batched.func1({0xc0002d64d0?, 0x0?, 0x0?})

/usr/local/go/src/crypto/rand/rand.go:38 +0x90

crypto/rand.(*reader).Read(0xc000037780, {0xc0002d64d0, 0x10, 0x10})

/usr/local/go/src/crypto/rand/rand_unix.go:56 +0x108

io.ReadAtLeast({0xcfaa60, 0xc000037780}, {0xc0002d64d0, 0x10, 0x10}, 0x10)

/usr/local/go/src/io/io.go:335 +0x90

io.ReadFull(...)

/usr/local/go/src/io/io.go:354

github.com/gofrs/uuid.(*Gen).NewV4(0xc000616b90)

/go/pkg/mod/github.com/gofrs/uuid@v4.4.0+incompatible/generator.go:262 +0x51

github.com/gofrs/uuid.NewV4(...)

/go/pkg/mod/github.com/gofrs/uuid@v4.4.0+incompatible/generator.go:62

github.com/bbernhard/signal-cli-rest-api/client.(*JsonRpc2Client).GetReceiveChannel(0xc0006163c0)

/tmp/signal-cli-rest-api-src/client/jsonrpc2.go:173 +0x42

github.com/bbernhard/signal-cli-rest-api/client.(*SignalClient).GetReceiveChannel(0x0?)

/tmp/signal-cli-rest-api-src/client/client.go:738 +0x85

github.com/bbernhard/signal-cli-rest-api/api.(*Api).handleSignalReceive(0xc0000a68f8, 0xc000dac420, {0xc00049e0a0, 0xd}, 0xc0004981e0)

/tmp/signal-cli-rest-api-src/api/api.go:393 +0x50

created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive in goroutine 105

/tmp/signal-cli-rest-api-src/api/api.go:513 +0x234

goroutine 49 [select]:

github.com/bbernhard/signal-cli-rest-api/api.(*Api).handleSignalReceive(0xc0000a68f8, 0xc000392580, {0xc000388130, 0xd}, 0xc0003942a0)

/tmp/signal-cli-rest-api-src/api/api.go:400 +0x172

created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive in goroutine 102

/tmp/signal-cli-rest-api-src/api/api.go:513 +0x234

goroutine 114 [select]:

github.com/bbernhard/signal-cli-rest-api/api.wsPing(0xc000392580, 0xc0003942a0)

/tmp/signal-cli-rest-api-src/api/api.go:470 +0x73

created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive in goroutine 102

/tmp/signal-cli-rest-api-src/api/api.go:514 +0x28d

goroutine 59 [select]:

github.com/bbernhard/signal-cli-rest-api/api.wsPing(0xc00034a580, 0xc0003502a0)

/tmp/signal-cli-rest-api-src/api/api.go:470 +0x73

created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive in goroutine 104

/tmp/signal-cli-rest-api-src/api/api.go:514 +0x28d

goroutine 108 [select]:

github.com/bbernhard/signal-cli-rest-api/api.wsPing(0xc000dac420, 0xc0004981e0)

/tmp/signal-cli-rest-api-src/api/api.go:470 +0x73

created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive in goroutine 105

/tmp/signal-cli-rest-api-src/api/api.go:514 +0x28d
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Thanks, I'll have a look

**Comment by bbernhard** [comment]
should be fixed. If you want to give it a try, here's a test version: `bbernhard/signal-cli-rest-api:0.144-dev`
