### ISSUE TITLE
Home Assistant multiple recipients

### ISSUE THREAD

**Issue by nagyrobi** [bbernhard/signal-cli-rest-api#6]
Sorry for asking here (if you want me I can coly to HA's issues), but how do I specify multiple recipients?

```yaml
  - name: Signal Csalad
    platform: signal_messenger
    url: "http://172.22.222.12:8080"
    number: "+XXXXXXXXXX"
    recipients:
      - "+AAAAAAAAA"
      - "+BBBBBBBBBB"
```
This only forwards messages only to +BBBBBBBBBB (the last one in the list).

**Comment by nagyrobi** [comment]
What I'm trying to achieve is to send notifications to 2 people, each time with 3 pictures.
Since sending to multiple recipients doesn't seem to work, I've set up the system to send notifications one by one to each recipient. And also because I need to send 3 pictures to each person, I have to send them one by one to each person. 

This adds up to the following:
```yaml
- alias: 'NotifGroup'
  trigger:
  - payload: on
    platform: mqtt
    topic: cmnd/bell/power
  action:
  - data: {}
    service: shell_command.csengo_pill_2
  - data:
      data:
        attachment: /tmp/csengo_pillanat_2.jpg
      message: Csengettek!
    service: notify.signal_robi
  - data:
      data:
        attachment: /tmp/csengo_pillanat_2.jpg
      message: Csengettek!
    service: notify.signal_zsu
  - data: {}
    service: shell_command.csengo_pill_3
  - data:
      data:
        attachment: /tmp/csengo_pillanat_3.jpg
      message: Csengettek!
    service: notify.signal_robi
  - data:
      data:
        attachment: /tmp/csengo_pillanat_3.jpg
      message: Csengettek!
    service: notify.signal_zsu
  - data: {}
    service: shell_command.csengo_pill_1
  - data:
      data:
        attachment: /tmp/csengo_pillanat_1.jpg
      message: Csengettek!
    service: notify.signal_robi
  - data:
      data:
        attachment: /tmp/csengo_pillanat_1.jpg
      message: Csengettek!
    service: notify.signal_zsu
 ```
The result is that some of the messages are delivered, some not. Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 47, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 71, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 68, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filename)
  File "/usr/local/lib/python3.7/site-packages/pysignalclirestapi/api.py", line 50, in send_message
    raise SignalCliRestApiError("Couldn't send signal message") from exc
pysignalclirestapi.api.SignalCliRestApiError: Couldn't send signal message
```

On the `signal-cli-rest-api` box I see:
```
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:48:32 | 201 |  4.773391702s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:48:43 | 201 |  7.575333918s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:49:44 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:49:58 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:50:09 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:50:23 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:53:18 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:53:29 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:53:40 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:54:09 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:54:20 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
signal-cli-rest-api_1  | [GIN] 2020/01/18 - 22:54:31 | 400 |          1m0s |  172.22.215.250 | POST     /v1/send
```

What's happening here?

Is the signal server banning sending messages so quickly? Or maybe signal-cli-rest-api can't cope with this?

**Comment by bbernhard** [comment]
see [here](https://github.com/AsamK/signal-cli/issues/259) for details.

**Comment by nagyrobi** [comment]
> see [here](https://github.com/AsamK/signal-cli/issues/259) for details.

OK, that's an explanation for my first comment. How about the second approach (send messages one by one).

**Comment by bbernhard** [comment]
The issue was fixed upstream by @AsamK.

There's no new docker image on dockerhub yet, but you can build it yourself in the meanwhile if you want. It should now be possible to send an attachment to multiple recipients. 

Sending multiple attachments to multiple recipients takes a bit more time, as this also needs changes in the Home Assistant codebase.

**Comment by nagyrobi** [comment]
Thank you. I'll be waiting for the final docker image and test then.

Also looking forward to updating the Home Assistant integration with the new codebase when it will be ready.

**Comment by bbernhard** [comment]
> Thank you. I'll be waiting for the final docker image and test then.

The image should be on dockerhub.

**Comment by bbernhard** [comment]
Support for multiple attachments should now be in Home Assistant 0.106.
