### ISSUE TITLE
rest-api temporarily unavailable from Homeassistant

### ISSUE THREAD

**Issue by Boebbele** [bbernhard/signal-cli-rest-api#614]
### The problem

signal-rest api works in a Docker container. Everything works well. The connection to Homeassistant also works...for a few hours. Here I have a problem:
My server terminates all running processes (Docker, Homeassistant, etc.) at night to create a complete system backup. After that, all processes start again. After that, signal _rest_api in Homeassistant generates an error when sending a message:

Logger: homeassistant.components.automation.nachricht_haustur_auf
Quelle: helpers/script.py:526
Integration: Automatisierung (Dokumentation, Probleme)
Erstmals aufgetreten: 07:03:17 (2 Vorkommnisse)
Zuletzt protokolliert: 08:10:52

*Nachricht_Haustür_auf: Error executing script. Unexpected error for call_service at pos 3: Specified account does not exist
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/notify/legacy.py", line 256, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/notify/legacy.py", line 236, in async_send_message
    await self.hass.async_add_executor_job(
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/signal_messenger/notify.py", line 118, in send_message
    self._signal_cli_rest_api.send_message(
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pysignalclirestapi/api.py", line 255, in send_message
    raise exc
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pysignalclirestapi/api.py", line 250, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: Specified account does not exist*

If I restart the signal docker container it usually works again. Sometimes I have to restart the whole docker process to get it working again.

What can I do?

My docker compose yml:

version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc
      - TZ=Europe/Berlin
    ports:
      - 8090:8080 # map docker port 8080 to host port 8090.
    volumes:
      - /home/dockervolumes/signal/signal-cli-config:/home/.local/share/signal-cli # map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped
networks: {}

I'm testing it now with MODE=normal. Maybe it will help?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

Homeassistant works as host installation on dietpi x86.
signal-rest-api works on the same server in a docker container. There are no errors in signal-rest-api container terminal output.

**Comment by Boebbele** [comment]
2 days it works stable. Today the same Problem:

Logger: homeassistant.components.automation.frigate_notification
Quelle: components/automation/__init__.py:743
Integration: Automatisierung (Dokumentation, Probleme)
Erstmals aufgetreten: 07:43:30 (1 Vorkommnisse)
Zuletzt protokolliert: 07:43:30

While executing automation automation.frigate_notification
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/automation/__init__.py", line 743, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/notify/legacy.py", line 256, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/notify/legacy.py", line 236, in async_send_message
    await self.hass.async_add_executor_job(
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/homeassistant/components/signal_messenger/notify.py", line 118, in send_message
    self._signal_cli_rest_api.send_message(
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pysignalclirestapi/api.py", line 255, in send_message
    raise exc
  File "/home/homeassistant/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pysignalclirestapi/api.py", line 250, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: Error while checking account +497073852021: java.net.UnknownHostException: chat.signal.org: Temporary failure in name resolution

**Comment by bbernhard** [comment]
`java.net.UnknownHostException: chat.signal.org: Temporary failure in name resolution`

That sounds like a problem in either your infrastructure or a temporary Signal Server error
