### ISSUE TITLE
Error Message: 1735081202014java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mike4001** [bbernhard/signal-cli-rest-api#634]
### The problem

Every time I send a Signal message via the Home Assistant Notify Service I get the following error message in my Logs. But the message gets sent and received.

`1735081202014java.lang.UnsatisfiedLinkError: org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(JZ)V [symbol: Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks or Java_org_signal_libsignal_internal_Native_LookupRequest_1setReturnAcisWithoutUaks__JZ] at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152) at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54) at org.signal.libsignal.internal.Native.LookupRequest_setReturnAcisWithoutUaks(Native Method) at org.signal.libsignal.net.CdsiLookupRequest$NativeRequest.<init>(CdsiLookupRequest.java:85) at org.signal.libsignal.net.CdsiLookupRequest.makeNative(CdsiLookupRequest.java:48) at org.signal.libsignal.net.CdsiLookup.start(CdsiLookup.java:19) at org.signal.libsignal.net.Network.cdsiLookup(Network.java:109) at org.whispersystems.signalservice.api.services.CdsiV2Service.lambda$new$1(CdsiV2Service.java:59) at org.whispersystems.signalservice.api.services.CdsiV2Service.getRegisteredUsers(CdsiV2Service.java:76) at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsersWithCdsi(SignalServiceAccountManager.java:249) at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsersV2(RecipientHelper.java:238) at org.asamk.signal.manager.helper.RecipientHelper.getRegisteredUsers(RecipientHelper.java:187) at org.asamk.signal.manager.helper.RecipientHelper.refreshUsers(RecipientHelper.java:156) at org.asamk.signal.manager.jobs.RefreshRecipientsJob.run(RefreshRecipientsJob.java:15) at org.asamk.signal.manager.internal.JobExecutor.lambda$runNextJob$0(JobExecutor.java:59) at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596) at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583) at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833) at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)`

Does anyone know whats the problem here and how I can fix it?

Merry Christmas! :-)

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

armv7

**Comment by mike4001** [comment]
Ok, seems to be a known bug

https://github.com/haberda/hassio_addons/issues/91
https://github.com/AsamK/signal-cli/issues/1642

**Comment by bbernhard** [comment]
should be fixed with the next release

**Comment by marvinruder** [comment]
I experience the same issue, and I also cannot easily go back to a previous version:

```
java.sql.SQLException: Database has been updated by a newer signal-cli version (RuntimeException)
```

@bbernhard Is there any known workaround, or an ETA for the next release?

**Comment by bbernhard** [comment]
> I experience the same issue, and I also cannot easily go back to a previous version:
> 
> ```
> java.sql.SQLException: Database has been updated by a newer signal-cli version (RuntimeException)
> ```
> 
> @bbernhard Is there any known workaround, or an ETA for the next release?

Please give this version a try: `bbernhard/signal-cli-rest-api:0.176-dev`

**Comment by marvinruder** [comment]
> Please give this version a try: `bbernhard/signal-cli-rest-api:0.176-dev`

Yes, this version works without a problem.
